# Generated by Django 6.0.6 on 2026-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец')], default='buyer', max_length=10, verbose_name='Роль'),
        ),
    ]
